plugins {
	id 'java'
	id 'jvm-test-suite'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

testing {
	suites {
		jackson3(JvmTestSuite) {
			dependencies {
				implementation project()
			}

			targets {
				all {
					testTask.configure {
						shouldRunAfter(test)
					}
				}
			}
		}

		jackson2(JvmTestSuite) {
			dependencies {
				implementation project()
			}

			targets {
				all {
					testTask.configure {
						shouldRunAfter(test)
					}
				}
			}
		}
	}
}


dependencies {
	jackson3Implementation platform('org.springframework:spring-framework-bom:7.0.0-RC1')
	jackson3Implementation platform('tools.jackson:jackson-bom:3.0.0')
	jackson3Implementation 'org.springframework:spring-aop'
	jackson3Implementation  'tools.jackson.core:jackson-databind'
	jackson3Implementation platform('org.assertj:assertj-bom:3.27.6')
	jackson3Implementation 'org.assertj:assertj-core'
	jackson3RuntimeOnly 'org.junit.platform:junit-platform-launcher'

	jackson2Implementation platform('org.assertj:assertj-bom:3.27.6')
	jackson2Implementation platform('org.springframework:spring-framework-bom:7.0.0-RC1')
	jackson2Implementation platform('com.fasterxml.jackson:jackson-bom:2.20.0')
	jackson2Implementation 'org.springframework:spring-aop'
	jackson2Implementation 'com.fasterxml.jackson.core:jackson-databind'
	jackson2Implementation 'org.assertj:assertj-core'
	jackson2RuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('check') {
	dependsOn(testing.suites.jackson2)
	dependsOn(testing.suites.jackson3)
}
