= Instructions

Your are likely viewing this because you have submitted a forum question or a JIRA and this is a sample project to illustrate points made in my response.
You can either run this from the commandline or an IDE that supports Maven (i.e. Spring Tool Suite).

== Running from the commandline

To run the sample application you must have Java installed and on your path.
After doing so you can easily run the application.
Specifically:

* Navigate to the folder on the commandline
* To Start the application Linux based users use

+

[source,bash]
----
./gradlew appRun
----

+

Windows users use

+

[source,bat]
----
.\gradlew.bat appRun
----

* Open http://localhost:8080/ in your browser
* You can log in with user/password
* To stop the container use Ctrl-C from the commandline


== Running test from the commandline

To run the tests you must have Java installed and on your path.
After doing so you can easily run the tests.
Specifically:

* Navigate to the folder on the commandline
* Linux users can run

+

[source,bash]
----
./gradlew check
----

+

Windows users use

+

[source,bat]
----
.\gradlew.bat check