spring.application.name: demo

spring:
  security:
    oauth2:
      client:
        provider:
          sample:
            issuer-uri: # Issuer
        registration:
          sample:
            client-id: "spring"
            client-secret: "secret"
server:
  port: 8080

debug: true
